districts = {
  "SYR": 
    { "doc_type":["Writtem Summáry of Restraint Use Procedures", # We're going to use doc_type to count how many reports are included in a pdf file
                  'Written Summary of Staff/Student Restraint Use Procedures',
                  'Written Summáry of Staff/Student Restraint Use Procedures',
                  'Written Summary of Staff/Student Restraint Use.Procedures', 
                  'Writter ef Use Prossibures',
                  'Restraimt Use Procedunres',
                  'INVESTIGATION REPORT',
                  "Incident Report Form",
                  'Physical Restraint Documentation form',
                  'Physical Restraint Documentation Form',
                  'Physical Restraint Incident Documentation Form',
                  'Restraint Documentation Form',
                  'Incident / Accident Report', 
                  'STANDARD STUDENT ACCIDENT REPORT FORM'], 
    "incident_date": ["Date of restraint:",
                      'Date of reséraint:',
                      'Date of Incident:',
                      'Date Occurred:',
                      'apate of restraints',
                      ],
    "time_began": ["Time began"],
    "time_ended": ["Time ended"],
    'duration': ['Time/Duration of Physical Restraint:'],
    "restraint_type": ["Nature of restraint (describe type of physical restraint used)",
                        'Which restraint was used (Please describe the restraint)'],


    "description": ["Explain student behavior(s) that prompted physical restraint",
                            'TO THE PRINCIPAL',
                            'NARRATIVE',
                            'Narrative / Notifications:',
                            'Description and location of physical restraint'
                            ],
    "injury": ["Note any injuries to student and/or staff that may have occured",
              "Information known about the resulting injury(ies)",
              'Medical findings (regarding student and staff)',
              "Note any injuries to student and/or staff that may have occurred:"
              ] 
},

  "mon1" : {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "mon2": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "ont": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "SUL": {
    "doc_type":['BEHAVIORAL INCIDENT REPORT',
                "Physical Intervention Incident Report"],
    'school_name':['Program:',
                  'Program'],
    "incident_date": ["Date of Incident:",
                      "Day, Date and Time of Incident"],
    'duration': ['Duration of Hold:',
                  'Duration of hold:'],
    "restraint_type": ["Type of Hold:",
                        "Type of hold:",
                        "Type of Physical Intervention Used:"],
    'description': ["What Happened?",
                    "What happened?",
                    "Happened?",
                    "Description of Incident"],
    "injury": ["Nurse Assessment/Observations:" ]
  },

  "TROY": {
    "doc_type":['PHYSICAL RETRAINT REPORT','PHYSICAL INTERVENTION/PHYSCIAL RESTRAINT REPORT'],
    'school_building':['School Bldg:','School:'],
    "incident_date": ["Date of Incident:"],
    'start_time': ['Start:'],
    'end_time':['End:','Time of Incident(length):'],
    "restraint_type": ["Describe Physical Involvement/Type of Restraint:",'Describe Physical Involvement(be sepecific):'],
    "description": ["Description of Incident:"],
    "injury": ["Medical Report/Nurses Note:","Nurse's Observational Report:"]
  },
  "roc": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "cob": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "ASSS": {
    "doc_type":['Physical Restraint Documentation Form','Time Out Room Log'],
    'student_id':['SchoolTool Student ID Number'],
    "incident_date": ["Incident Date:",'Date:'],
    "start_time": ["Start Time:", 'Time entered:'],
    "end_time": ["End Time:",'Time exited:'],
    "restraint_type": ["Please check which TCIS physical restraint was employed:Standing Restraint",'Please check which TCIS physical restraint was employed:'],
    "description": ["Describe the situtaion that led to the use of physical restraint(be specific with behaviors; what did the student say and do; what did the staff say and do; and name all staff involved):","Precipitating Factors (describe)",
    'sav and do; what did the staff say and do; and name all staff involved):',
    'say and do; what did the staff say and do; and name all staff involved):',
    'Precipitating Factors (describe) while playing tag .',
    'Precipitating Factors (describe) After given instructions For'],
  },
  "NOCO": {
    "doc_type":['ASC Time Out Room Log',
                'Incident Involving an Emergency Intervention',
                'Incident Involving a Physical Restraint',
                'Health Office Visit Report'],
   #'school_name':'',
    "incident_date": ["Date:"],
    'incident_time': ['Start Time-'], # look for the first item in the list
    #"report_date": "",
    'grade':["Grade:"],
    'duration': ['Elapsed Time:',
                  'uration:',
                  'Duration:'],
    "restraint_type": ["Emergency Intervention(s) used:",
                      'Incident Involving a Physical Restraint',
                      'ASC TIME Out Room',
                      'ASC Time Out Room'
                      ],
    #"staff": "",
    "description":[ "Circumstances that precipitated use of time out room:",
                  'Description of Incident: (Please include all relevant detail. Use attachments if necessary.)',
                  'Description of Incident:'
                  ],
    #'restraint_description': "",
    #'location': "",
    "injury": ["If yes, please describe.",
              "Was there any apparent injury to the student(s) or district employee(s)?"]
  },
  "tntp": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "SCH": {
    "doc_type":['Report - Incident Involving Therapeutic Physical Restraint',
                "HEALTH OFFICE",
                "PHYSICAL RESTRAINT REPORT"],
    "incident_date": ["Date of incident:",
                      "Date:"],
    "school":["Name of School Building:",
              "Building:"],
    'duration': ["Complete Time of Restraint"],
    'start_time':["What time did the physcial restraint begin?",
                  "What time did the physical restraint begin?"],
    "end_time":["What time did the physical restraint end?"],
    "student_id":["Student ID:"],
    "restraint_type": ["Which TCIS physcial restraint technique was used?"],# next six lines
    "description": ["interventions used preceding the restraint).",
                    "'interventions used preçeding the restraint).",
                    "What led up to the student's unsafe behavior?"], # next five lines
    'grade':["Grade","Grade:"],
    "student_injury":["To the Student (nature of injury):",
                      "List any physical complaints that the student made.",
                      "Record any signs of injury to the student.",
                      "Assessment of Student"],
    "adult_injury":["To Adults (names):"] # next three lines
  },
  "COH": {
    "doc_type":['CPI Physical Restraint and/or Seclusion Incident Report'],
    'school_name':['School:'],
    "incident_date": ["Date of Incident:"],
    "restraint_began": ["Time restraint began:"],
    "seclusion_began":["Time seclusion began:"],
    "restraint_ended":["Time restraint ended:"],
    "seclusion_ended": ["Time seclusion ended:"],
    "restraint_type": ["Nonviolent Physical Crisis Intervention(s) (NPCI) used:"],
    'description': ["Description of student's specific behaviors justifying physical restraint and/or seclusion:"],
  },
  "GLEN": {
    "doc_type":['Physical Invervention/ Physical Restraint Report',
                "Physical Intervention/Physical Restraint Report",
                "Physical Intervention/ Physical Restraint Report",
                "Critical Incident Report"],
    "grade":["Grade/Class"],
    'school_name':['School:'],
    "incident_date": ["Date of Incident:"],
    'duration': ['Time of Incident(Length):',
                'Time of Incident (length):',
                "Time of Incident (Length):",
                "Length of Incident:",
                "Time of Incident (length):"],
    "restraint_type": ["Describe Physical Involvement(be specific):",
                        "Describe Physical Involvement (be specific):",
                      "Type of physical intervention/restraint(if applicable):"],
    "description": [
                    "Description of Incident:",
                    "Description of Incident(be specific):"],
    "injury": ["Nurse's Observational Report:",
              "Observational Denus Report:",
              "Observational Report:",
              "Nurse's olservational",
              "Nurse's Observational"] # next line
  },
  "alb": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "BALL": {
    "doc_type":['Notification of Use of Physical Intervention',
                "Time Out Room Log"],
    'school_name':['School:',
                    'School(BOCES Site):'],
    "incident_date": ["Incident Date:",
                      "Date:"],
    'duration': ['Duration of Restraint:'],
    'start_time':["Time entered:"],
    'exit_time':['Time exited:'],
    "restraint_type": ["Please check which physical interventions were employed:"]
  },
  "kat": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "nyc": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "buf": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "wat": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "beth": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "BRI": {"doc_type":['Escort/ Restraint',
                      "ESCORT/RESTRAINT"],
    "incident_date": ["Date:"],
    "time_began": ["Start Time:"],
    "time_ended": ["Stop Time:"],
    "restraint_type": ["Unsuccessful"], # next five lines
    "description": ["Precipitating Factors/Description of Escort/Restraint"]}
}

