districts = {
  "syr": 
    { "doc_name":["Writtem Summáry of Restraint Use Procedures", # We're going to use doc_type to count how many reports are included in a pdf file
                  'Written Summary of Staff/Student Restraint Use Procedures',
                  'Written Summáry of Staff/Student Restraint Use Procedures',
                  'Written Summary of Staff/Student Restraint Use.Procedures', 
                  'Writter ef Use Prossibures',
                  'Restraimt Use Procedunres',
                  "INCIDENT REPORT FORM",
                  'INVESTIGATION REPORT',
                  "Incident Report Form",
                  'Physical Restraint Documentation form',
                  'Physical Restraint Documentation Form',
                  'Physical Restraint Incident Documentation Form',
                  'Restraint Documentation Form',
                  'Incident / Accident Report', 
                  'STANDARD STUDENT ACCIDENT REPORT FORM'], 

    'school_name': 'FROM-',

    "incident_date": ["Date of restraint",
                      'Date of reséraint',
                      "DATE/TIME OF INCIDENT",
                      'Date of Incident',
                      'Date Occurred',
                      'apate of restraints',
                      ],

    'incident_time': ['Time'],
    "report_date": ["DATE/TIME INCIDENT REPORT"],
    "time_began": ["Time began"],
    "time_ended": ["Time ended"],
    'duration': ['Time/Duration of Physical Restraint'],

    "restraint_type": ["Nature of restraint (describe type of physical restraint used)",
                        'Which restraint was used (Please describe the restraint)'],

    "staff": ["Name(s) of staff member(s) adminstering restraint",
            "NAME OF PERSON GIVING TESTIMONY",
            'Staff involved in the physical restraint',
              ],

    "incident_description": ["Explain student behavior(s) that prompted physical restraint",
                            'TO THE PRINCIPAL',
                            'NARRATIVE',
                            'Narrative / Notifications:'
                            ],
    'restraint_description': ['Description and location of physical restraint'],

    'location': ['Description and location of physical restraint'],

    "injury": ["Note any injuries to student and/or staff that may have occured",
              "Information known about the resulting injury(ies)",
              'Medical findings (regarding student and staff)',
              ] 
},

  "mon1" : {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "mon2": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "ont": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "sul": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "TROY": {
    "doc_type":['PHYSICAL RETRAINT REPORT','PHYSICAL INTERVENTION/PHYSCIAL RESTRAINT REPORT'],
    'school_building':['School Bldg:','School:'],
    "incident_date": ["Date of Incident:"],
    'start_time': ['Start:'],
    'end_time':['End:','Time of Incident(length):'],
    "restraint_type": ["Describe Physical Involvement/Type of Restraint:",'Describe Physical Involvement(be sepecific):'],
    "description": ["Description of Incident:"],
    "injury": ["Medical Report/Nurses Note:","Nurse's Observational Report:"]
  },
  "roc": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "cob": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "asss": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "NOCO": {
    "doc_type":['ASC Time Out Room Log',
                'Incident Involving an Emergency Intervention',
                'Incident Involving a Physical Restraint',
                'Health Office Visit Report'],
   #'school_name':'',
    "incident_date": ["Date:"],
    'incident_time': ['Start Time-'], # look for the first item in the list
    #"report_date": "",
    'grade':["Grade:"],
    'duration': ['Elapsed Time:',
                  'uration:',
                  'Duration:'],
    "restraint_type": ["Emergency Intervention(s) used:",
                      'Incident Involving a Physical Restraint',
                      'ASC TIME Out Room',
                      'ASC Time Out Room'
                      ],
    #"staff": "",
    "description":[ "Circumstances that precipitated use of time out room:",
                  'Description of Incident: (Please include all relevant detail. Use attachments if necessary.)',
                  'Description of Incident:'
                  ],
    #'restraint_description': "",
    #'location': "",
    "injury": ["If yes, please describe.",
              "Was there any apparent injury to the student(s) or district employee(s)?"]
  },
  "tntp": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "sch": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "coh": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "glen": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "alb": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "ball": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "kat": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "nyc": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "buf": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "wat": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "beth": {
    "doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""
  },
  "bri": {"doc_type":'',
    'school_name':'',
    "incident_date": "",
    'incident_time': '',
    "report_date": "",
    "time_began": "",
    "time_ended": "",
    'duration': '',
    "restraint_type": "",
    "staff": "",
    "incident_description": "",
    'restraint_description': "",
    'location': "",
    "injury": ""}
}

